Update Main Branch
marconicivitavecchia/Instagram-Follower-Counter pull request #32
Opened 2023-11-17 06:13 UTC by FThinker

Fixed IP getting blocked by using a rotating proxy, increased request interval to 2 seconds.

2023-11-17 16:15 UTC, DavideSky requested changes
@marconicivitavecchia/backend Date un'occhiata ai commenti sui commit, quando si risolve tutto facciamo il merge

2023-11-17 16:15 UTC, DavidePiccione commented on Backend/mqtt.js
@marconicivitavecchia/backend Le credenziali qui sono quelle attualmente usate? In caso non dovrebbero essere su Github

2023-11-17 16:15 UTC, DavidePiccione commented on Frontend/app.js
@marconicivitavecchia/backend avete modificato un file del gruppo @marconicivitavecchia/frontend , siete entrambi d'accordo con le modifiche?

I file modificati sono:
- app.js
- data.json
- index.html
- style.css

2023-11-17 16:15 UTC, DavidePiccione commented on documentazione
@marconicivitavecchia/backend La documentazione va messa nel README.md che si trova nella vostra repository

2023-11-17 16:19 UTC, DavideSky requested changes

2023-11-17 16:19 UTC, DavideSky commented on Backend/mqtt.js
@marconicivitavecchia/backend dovreste risolvere anche questa issue prima di fare il merge:
https://github.com/marconicivitavecchia/IFC-Backend-dev/issues/4#issuecomment-1815844691

2023-11-17 16:31 UTC, FThinker commented on Backend/mqtt.js
No, non ci sono più le credenziali nel codice, le abbiamo tolte direttamente

2023-11-17 16:32 UTC, FThinker commented on Frontend/app.js
No, li abbiamo modificati solo per motivi di testing, non vogliamo portare avanti quelle modifiche.

2023-11-17 16:32 UTC, FThinker commented on documentazione
@brucobruce @Splyxxx

2023-11-17 16:32 UTC, FThinker commented on Backend/mqtt.js
@brucobruce @Splyxxx

2023-11-17 16:39 UTC, DavideSky commented on Backend/mqtt.js
Quindi confermate che dove c'è scritto:
```python
username: 'emqx',
password: 'public',
 ```
 
 non sono credenziali attualmente usate?

2023-11-17 16:40 UTC, DavideSky commented on Frontend/app.js
Va bene, ora allora vediamo di toglierli dalla PR

2023-11-17 17:06 UTC, DavideSky commented on Backend/mqtt.js
Per ora va risolviamo con il commit d950aba, però nel prossimo sprint aggiungete tutte le credenziali in un file credentials.json che lasciate in locale senza metterlo su github. Per escluderlo dai commit aggiungete credentials.json nel .gitignore

2023-11-17 17:14 UTC, Kylessh commented on Backend/mqtt.js
Affermativo, lo faremo.

2023-11-19 11:01 UTC, DavideSky commented on documentazione
@brucobruce va bene il commit da4b168, ma dovete anche **eliminare** il file che si chiama "documentazione" che sta fuori dalla cartella backend. La documentazione poi andrebbe formattata. Trovate un esempio in questo file:
| **Codice Sorgente** | **Risultato Finale**|
|--------|--------|
| *[Source Code](https://github.com/marconicivitavecchia/Instagram-Follower-Counter/blob/dev/docs/guidelines/code.rst?plain=1)* | [Result](https://instagram-follower-counter.readthedocs.io/it/latest/guidelines/code.html)|

2023-11-19 18:13 UTC, DavideSky commented on documentazione
Va bene il commit 677e8a9 per eliminare il file "documentazione", rimangono però questi due punti che devono ancora essere risolti:
1. Dovete formattare correttamente la documentazione come già indicato nel commento precedente
2. Dovete risolvere questa issue: https://github.com/marconicivitavecchia/IFC-Backend-dev/issues/4

2023-11-19 19:10 UTC, FThinker commented on documentazione
Lo so, stiamo aspettando @brucobruce @Splyxxx

2023-11-28 09:26 UTC, DavideSky approved these changes
### Warning: README.rst is still Work in Progress

2023-11-28 09:26 UTC, merged